name: AD Management

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-ad:
    runs-on: self-hosted

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run AD script
        shell: powershell
        run: |
          cd scripts
          .\apply.ps1
